[units]
# plural_form = ["singular form",  "alias 1", "alias 2", ...]

# Time
nanoseconds = ["nanosecond",  "ns", "nsec"]
microseconds = ["microsecond",  "µs", "µsec", "us", "usec"]
milliseconds = ["millisecond",  "ms", "msec"]
seconds = ["second",  "s", "sec"]
minutes = ["minute",  "m", "min"]
hours = ["hour",  "h", "hr", "hrs"]
days = ["day",  "d"]
weeks = ["week",  "wk"]
years = ["year",  "y", "yr", "yrs"]
months = ["month",  "mo"]
decades = ["decade"]
centuries = ["century"]
millennia = ["millennium",  "kiloyear"]

# Data size in bits (both SI and binary)
bits = ["bit",  "b"]
kilobits = ["kilobit",  "Kb", "kb", "kbit"]
kibibits = ["kibibit",  "Kib", "kib"]
megabits = ["megabit",  "Mb", "mbit"]
mebibits = ["mebibit",  "Mib"]
gigabits = ["gigabit",  "Gb", "gbit"]
gibibits = ["gibibit",  "Gib"]
terabits = ["terabit",  "Tb", "tbit"]
tebibits = ["tebibit",  "Tib"]
petabits = ["petabit",  "Pb", "pbit"]
pebibits = ["pebibit",  "Pib"]
# Data size in bytes (both SI and binary)
bytes = ["byte",  "B"]
kilobytes = ["kilobyte",  "KB", "kB"]
kibibytes = ["kibibyte",  "KiB", "kiB"]
megabytes = ["megabyte",  "MB"]
mebibytes = ["mebibyte",  "MiB"]
gigabytes = ["gigabyte",  "GB"]
gibibytes = ["gibibyte",  "GiB"]
terabytes = ["terabyte",  "TB"]
tebibytes = ["tebibyte",  "TiB"]
petabytes = ["petabyte",  "PB"]
pebibytes = ["pebibyte",  "PiB"]

# Energy
joules = ["joule",  "J"]
kilojoules = ["kilojoule",  "kJ"]
electronvolts = ["electronvolt",  "electron-volt", "electron volt", "electron-volts", "electron volts", "eV"]

# Power
milliwatts = ["milliwatt",  "mW"]
watts = ["watt",  "W"]
kilowatts = ["kilowatt",  "kW"]
megawatts = ["megawatt",  "MW"]
gigawatts = ["gigawatt",  "GW"]

# Frequency
hertz = ["hertz",  "Hz"]
kilohertz = ["kilohertz",  "KHz", "kHz"]
megahertz = ["megahertz",  "MHz"]
gigahertz = ["gigahertz",  "GHz"]
terahertz = ["terahertz",  "THz"]

# Length (metric)
nanometers = ["nanometer",  "nm"]
micrometers = ["micrometer",  "µm", "um"]
millimeters = ["millimeter",  "mm"]
centimeters = ["centimeter",  "cm"]
meters = ["meter",  "m"]
kilometers = ["kilometer",  "km"]
# Length (imperial)
inches = ["inch",  "in", '"']
feet = ["foot",  "ft"]
yards = ["yard",  "yd"]
miles = ["mile",  "mi"]
"nautical miles" = ["nautical mile",  "NM"]

# Mass (metric)
micrograms = ["microgram",  "µg", "ug"]
milligrams = ["milligram",  "mg"]
grams = ["grams",  "g"]
kilograms = ["kilogram",  "kg"]
"metric tons" = ["metric ton",  "mt", "Mt"]
# Weight (imperial)
ounces = ["ounce",  "oz"]
pounds = ["pound",  "lb", "lbs"]
stones = ["stone",  "st"]
tons = ["ton",  "T"]

# Pressure
pascals = ["pascal",  "Pa"]
bars = ["bar",  "Bar"]
torr = ["torr",  "Torr"]
atmospheres = ["atmosphere",  "atm"]

# Volume (metric)
milliliters = ["milliliter",  "mL"]
liters = ["liter",  "L"]
"cubic meters" = ["cubic meter",  "m³", "m3"]
# Volume (US imperial)
"cubic inches" = ["cubic inch",  "in³", "in3"]
"fluid ounces" = ["fluid ounce",  "fl oz.", "fl oz"]
"cubic feet" = ["cubic foot",  "ft³", "ft3"]
cups = ["cup",  "c", "C"]
teaspoons = ["teaspoon",  "tsp", "t"]
pints = ["pint",  "pt"]
quarts = ["quart",  "qt"]
gallons = ["gallon",  "gal"]
tablespoons = ["tablespoon",  "T", "TB", "Tbl", "Tbsp"]


[conversions]
# "[from amount] [from unit]", '[to amount] [to unit]"
# Plural units are used here for simplicity, even for singular amounts
table = [
    # Time
    "1 microseconds", "1000 nanoseconds",
    "1 milliseconds", "1000 microseconds",
    "1 seconds", "1000 milliseconds",
    "60 seconds", "1 minutes",
    "60 minutes", "1 hours",
    "24 hours", "1 days",
    "7 days", "1 weeks",
    "365.25 days", "1 years",
    "30.4167 weeks", "1 months",
    "52 weeks", "1 years",
    "12 months", "1 years",
    "10 years", "1 decades",
    "100 years", "1 centuries",
    "1000 years", "1 millennia",

    # Data size in bits (both SI and binary)
    "1000 bits", "1 kilobits",
    "1024 bits", "1 kibibits",
    "1000 kilobits", "1 megabits",
    "1024 kibibits", "1 mebibits",
    "1000 megabits", "1 gigabits",
    "1024 mebibits", "1 gibibits",
    "1000 gigabits", "1 terabits",
    "1024 gibibits", "1 tebibits",
    "1000 terabits", "1 petabits",
    "1024 petabits", "1 pebibits",
    # Data size in bytes (both SI and binary)
    "8 bits", "1 bytes",
    "1000 bytes", "1 kilobytes",
    "1024 bytes", "1 kibibytes",
    "1000 kilobytes", "1 megabytes",
    "1024 kibibytes", "1 mebibytes",
    "1000 megabytes", "1 gigabytes",
    "1024 mebibytes", "1 gibibytes",
    "1000 gigabytes", "1 terabytes",
    "1024 gibibytes", "1 tebibytes",
    "1000 terabytes", "1 petabytes",
    "1024 petabytes", "1 pebibytes",

    # Energy
    "1000 joules", "1 kilojoules",
    "1 joules", "6242000000000000000 electronvolts",

    # Power
    "1000 milliwatts", "1 watts",
    "1000 watts", "1 kilowatts",
    "1000 kilowatts", "1 megawatts",
    "1000 megawatts", "1 gigawatts",

    # Frequency
    "1000 hertz", "1 kilohertz",
    "1000 kilohertz", "1 megahertz",
    "1000 megahertz", "1 gigahertz",
    "1000 gigahertz", "1 terahertz",

    # Length (metric)
    "1000 nanometers", "1 micrometers",
    "1000 micrometers", "1 millimeters",
    "1000 millimeters", "1 meters",
    "100 centimeters", "1 meters",
    "1000 meters", "1 kilometers",
    # Length (imperial)
    "12 inches", "1 feet",
    "3 feet", "1 yards",
    "5280 feet", "1 miles",
    "6076 feet", "1 nautical miles",
    # Length (cross-system)
    "1 inches", "2.54 centimeters",

    # Mass (metric)
    "1000 micrograms", "1 milligrams",
    "1000 milligrams", "1 grams",
    "1000 grams", "1 kilograms",
    "1000 kilograms", "1 metric tons",
    # Weight (imperial)
    "16 ounces", "1 pounds",
    "14 pounds", "1 stones",
    "2000 pounds", "1 tons",
    # Mass/weight (cross-system)
    "28.3495 grams", "1 ounces",

    # Pressure
    "100000 pascals", "1 bars",
    "133.322 pascals", "1 torr",
    "760 torr", "1 atmospheres",

    # Volume (metric)
    "1000 milliliters", "1 liters",
    "1000 liters", "1 cubic meters",
    # Volume (US imperial)
    "1 cubic inches", "0.554113 fluid ounces",
    "1728 cubic inches", "1 cubic feet",
    "240 milliliters", "1 cups",  # also cross-system
    "48.6922 teaspoons", "1 cups",
    "16 fluid ounces", "1 pints",
    "2 pints", "1 quarts",
    "4 quarts", "1 gallons",
    "256 tablespoons", "1 gallons",
    "3 teaspoons", "1 tablespoons",
]
